name: deploy

on:
  push:
    branches:
      - master

jobs:

  # Build executable Jar files and package as a Release
  deploy-release:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      DB_DATABASE: sifis_ptp
      DB_USER: root
      DB_PASSWORD: root
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
     
      - uses: actions/setup-java@v3
        with:
          java-version: 11.0.x
          architecture: x64
          distribution: 'zulu'
          cache: 'maven'

      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD}} 
          mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD}}  < schema.sql

      - name: Create the (jar) packages and libraries
        run: |
          ./scripts/build-ptp.sh 

      - name: Get version
        id: tagName
        run: |
          VERSION=$(cat ./VERSION)
          echo "tag=$VERSION" >> $GITHUB_OUTPUT

      - name: Build Zip file
        run: |
          ARCHIVE_NAME="policy-translation-point-${{ steps.tagName.outputs.tag }}"
          ARCHIVE_FILE="${ARCHIVE_NAME}.zip"
          zip -r ${ARCHIVE_FILE} apps/*.jar

      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.tagName.outputs.tag }}
          files: |
            ./*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}